dist: bionic
language: python

python:
- '3.6'

env:
  global:
  # GITHUB_ACCESS_TOKEN=
  -   secure: "TMSRG8Nliqg1TPkvgbaev6H8y6S7iFhUCENQd95bsm3tz4WRXCGpko+SGhGCqf5XRxYTJ0eAAExF4tXvoiybZ4cMJ6PS+1DqcMzJ0SRgqDPJSrjDEwFdpGoO+bhDFKwHfVkWJRZPI9o+LAFPDP/bhdZXfJXtfewdqz+ExqbyMMKb8FYmvUyJbPisnutJGqrTBCQBVdwtwQAVAwbnEbZcwCEwNkBLkhT18SgrFs3FIoKGoXKTur66+ptyP8IBEapxAMFWsNKkuHZMlkGjyPFM/QEvvHKExDrWBN2kWGEckGWECXxLwzFtYzti4tcQICop62cynbsm3luJLoWaT4wCTA9K5iy5xsjHY84VSZzHQedtwQMK5Ky8U0ifG3QokD0r3E7X8nRxqvvsa45RXAfRQe5m5u5nAtk5toKRkRG5IRPJjf+hJdR6yr2k51EZsZN8VsA+4y2Xpyo2LOwGZuw4AYdRpjq3yQ8yvgXIYZ1GS4NdQbDZ2DKNUSqJ9qL7lDkGud0yY+CRYpxsc+QN0SJLbvQK0i0hLbcrPrg+MxfNhpFQZptkvZQH93mWDNYNozOKFY/83m5ZNI3cPR+5UuifyOtOjmWyc+E8LFlCA5RNDENcvyz5Eqvz37XrENwSkt2ssOQt1RJ5479J/GO6b64py1nRrdg53DA36q/5TeGpCF8="
  - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
    PLAT=manylinux2010_x86_64
  jobs:
  - PYSLUG=None
  - PYSLUG=cp27-cp27m
  - PYSLUG=cp27-cp27mu
  - PYSLUG=cp35-cp35m
  - PYSLUG=cp36-cp36m
  - PYSLUG=cp37-cp37m
  - PYSLUG=cp38-cp38

before_install:
- sudo apt-get update
- sudo apt-get -y install $(tr '\n' ' ' < apt-requirements-bionic.txt)

install:
- pip install -r pip-requirements.txt;
- if [ "${PYSLUG}" != "None" ]; then
    docker pull $DOCKER_IMAGE;
  fi

script:
- mkdir ${TRAVIS_BUILD_DIR}/../cmake-build
- cd ${TRAVIS_BUILD_DIR}/../cmake-build
- cmake -G Ninja
  -DCMAKE_BUILD_TYPE=RelWithDebInfo
  -DCMAKE_INSTALL_PREFIX=./install
  ${TRAVIS_BUILD_DIR}
- if [ "${PYSLUG}" == "None" ]; then ninja; fi
- if [ "${PYSLUG}" == "None" ]; then ninja better-test; fi
- if [ "${PYSLUG}" == "None" ]; then ninja lint; fi
- if [ "${PYSLUG}" == "None" ]; then
    ninja pynix-wheel-localenv;
  else
    ninja pynix-wheel-${PYSLUG};
  fi

jobs:
  exclude:
  - python: '3.6'
    env:
    - PYSLUG=None
    - PYSLUG=cp27-cp27m
    - PYSLUG=cp27-cp27mu
    - PYSLUG=cp35-cp35m
    - PYSLUG=cp36-cp36m
    - PYSLUG=cp37-cp37m
    - PYSLUG=cp38-cp38
    if: repo = cheshirekow/pynix
        AND tag IS present
        AND tag =~ ^pseudo-((master)|(staging))$

  include:
  - stage: test
  - python: '2.7'
    env: PYSLUG=None
    if: repo = cheshirekow/pynix
        AND (tag IS NOT present
             OR tag =~ ^(?!pseudo-).*$)
  - stage: deploy
    name: deploy-tag
    if: repo = cheshirekow/pynix
        AND NOT tag IS present
        AND branch =~ ^((master)|(staging))$
    script:
    - python -B ${TRAVIS_BUILD_DIR}/tangent/tooling/github.py
        create-pseudorelease-tag cheshirekow/pynix ${TRAVIS_BRANCH}
  - name: deploy-artifacts
    if: repo = cheshirekow/pynix
        AND tag IS present
        AND (tag =~ ^pseudo-((master)|(staging))$
             OR tag =~ ^v\d+\.\d+\.\d+)
    script:
    - mkdir ${TRAVIS_BUILD_DIR}/../cmake-build
    - cd ${TRAVIS_BUILD_DIR}/../cmake-build
    - cmake -G Ninja
      -DCMAKE_BUILD_TYPE=RelWithDebInfo
      -DCMAKE_INSTALL_PREFIX=./install
      ${TRAVIS_BUILD_DIR}
    - ninja push-pynix-github-release
  - name: deploy-docs
    python: 3.6
    if: repo == cheshirekow/pynix
        AND tag IS present
        AND (tag =~ ^pseudo-((master)|(staging))$
             OR tag =~ ^v\d+\.\d+\.\d+)
    script:
    - mkdir ${TRAVIS_BUILD_DIR}/../cmake-build
    - cd ${TRAVIS_BUILD_DIR}/../cmake-build
    - cmake -G Ninja
      -DCMAKE_BUILD_TYPE=RelWithDebInfo
      -DCMAKE_INSTALL_PREFIX=./install
      ${TRAVIS_BUILD_DIR}
    - ninja push-pynix-rtd-repo

stages:
  - test
  - name: deploy
    if: type == push

